export const POSTS = {
  POSTS_GET_ALL_REQUEST: 'POSTS_GET_ALL_REQUEST',
  POSTS_GET_ALL_SUCCESS: 'POSTS_GET_ALL_SUCCESS',
  POSTS_GET_ALL_FAILURE: 'POSTS_GET_ALL_FAILURE',
  POSTS_SEARCH_REQUEST: 'POSTS_SEARCH_REQUEST',
  POSTS_SEARCH_SUCCESS: 'POSTS_SEARCH_SUCCESS',
  POSTS_SEARCH_FAILURE: 'POSTS_SEARCH_FAILURE',
};

export const COMMENTS = {
  COMMENTS_GET_ALL_REQUEST: 'COMMENTS_GET_ALL_REQUEST',
  COMMENTS_GET_ALL_SUCCESS: 'COMMENTS_GET_ALL_SUCCESS',
  COMMENTS_GET_ALL_FAILURE: 'COMMENTS_GET_ALL_FAILURE',
  COMMENTS_GET_BY_ID_POST_REQUEST: 'COMMENTS_GET_BY_ID_POST_REQUEST',
  COMMENTS_GET_BY_ID_POST_SUCCESS: 'COMMENTS_GET_BY_ID_POST_SUCCESS',
  COMMENTS_GET_BY_ID_POST_FAILURE: 'COMMENTS_GET_BY_ID_POST_FAILURE',
};

export const AUTH = {
  AUTH_REGISTER_REQUEST: 'AUTH_REGISTER_REQUEST',
  AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  AUTH_REGISTER_FAILURE: 'AUTH_REGISTER_FAILURE',
  AUTH_LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',
  AUTH_LOGOUT_REQUEST: 'AUTH_LOGOUT_REQUEST',
  AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  AUTH_LOGOUT_FAILURE: 'AUTH_LOGOUT_FAILURE'
};

export const USER_IDENTITY = {
  USER_IDENTITY_GET_INFO_REQUEST: 'USER_IDENTITY_GET_INFO_REQUEST',
  USER_IDENTITY_GET_INFO_SUCCESS: 'USER_IDENTITY_GET_INFO_SUCCESS',
  USER_IDENTITY_GET_INFO_FAILURE: 'USER_IDENTITY_GET_INFO_FAILURE'
};

export const DETAIL = {
  DETAIL_GET_POST_BY_ID_REQUEST: 'DETAIL_GET_POST_BY_ID_REQUEST',
  DETAIL_GET_POST_BY_ID_SUCCESS: 'DETAIL_GET_POST_BY_ID_SUCCESS',
  DETAIL_GET_POST_BY_ID_FAILURE: 'DETAIL_GET_POST_BY_ID_FAILURE'
}